## Overview

In [1]:
import numpy as np

In [3]:
l = [1,2,3, 'a']
l

[1, 2, 3, 'a']

In [5]:
arr = np.array(l)
arr

array(['1', '2', '3', 'a'], dtype='<U21')

In [6]:
l = [[1,2,3],[4,5,6]]
l

[[1, 2, 3], [4, 5, 6]]

In [7]:
a = np.array(l)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a.shape

(2, 3)

In [9]:
a1 = np.arange(1,11)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
a1.shape

(10,)

In [11]:
a2 = a1.reshape((2,5))
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
l = [[1,2,3],[4,5,6]]
a = np.array(l)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
print(l[1][1])
print(a[1,1])

5
5


In [24]:
l1 = [1,2,3]
l2 = [4,5,6]

l1 + l2

[1, 2, 3, 4, 5, 6]

In [26]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print(a1 + a2)
print(a1 * a2)

[5 7 9]
[ 4 10 18]


## Indexing and Slicing

In [27]:
a1 = np.arange(1,10)
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
print( a1[2] )
print( a1[2:] )

print( a1[-1])
print( a1[-3:])

3
[3 4 5 6 7 8 9]
9
[7 8 9]


In [34]:
a2 = a1[:-1].reshape((2,4))
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
print( a2[0,2] )
print( a2[0,2:] )


3
[3 4]


In [40]:
a2[:, 2:]

array([[3, 4],
       [7, 8]])